version: 2.1

jobs:
  lab04-data-pipeline:
    docker:
      - image: cimg/python:3.12
    steps:
      - checkout
      - run:
          name: Install Python deps
          command: |
            python -m pip install --upgrade pip
            python -m pip install -r lab04_data_pipeline/requirements.txt
      - run:
          name: Run pipeline (generate CSV, fit, plot) #as module so imports work
          command: python -m lab04_data_pipeline.scripts.run_pipeline
      - run:
          name: Run tests (as module; consistent interpreter + path)
          command: python -m pytest -q lab04_data_pipeline/tests
      - store_artifacts:
          path: lab04_data_pipeline/data
          destination: lab04_data_pipeline/data
      - store_artifacts:
          path: lab04_data_pipeline/outputs
          destination: lab04_data_pipeline/outputs

workflows:
  build-test:
    jobs:
      - lab04-data-pipeline
